- category: "Professional Activities"
  items:
    - "DEIM 2026 Junior Commentator / ジュニアコメンテータ"

- category: "International Conference"
  items:
    - "Reviewer (Conference): NeurIPS 2024, ICLR 2025, AISTATS 2025, ICML 2025, ACL ARR 2025, NeurIPS 2025 DB Track, ADMA 2025, ICLR 2026, ACL ARR 2026"
    - "Reviewer (Workshop): ICLR 2024 Workshop LLMAgents, ICML 2025 Workshop CFAgentic"
    - "External Reviewer: CIKM 2022, DASFAA 2023, KDD 2023, ADMA 2023, APWeb-WAIM 2024, ACL ARR 2024, ADMA 2024"

- category: "Journal"
  items:
    - "Reviewer: IEEE Access, European Journal of Engineering Education"

- category: "Professional Memberships"
  items:
    - "The Database Society of Japan (DBSJ)"
    - "The Association for Computational Linguistics (ACL)"
